/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ui;

import DAO.DatDoAnDAO;
import DAO.DoAnDAO;
import DTO.ChiTietDonHangDTO;
import Entity.DoAn;
import Utils.Auth;
import Utils.PriceUtils;
import com.microsoft.sqlserver.jdbc.StringUtils;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class DatDoJFrame extends javax.swing.JFrame {
    private final javax.swing.table.DefaultTableModel doAnModel = new DefaultTableModel();
    private final javax.swing.table.DefaultTableModel chiTietModel = new DefaultTableModel();
    private final DoAnDAO doAnDAO = new DoAnDAO();
    private final DatDoAnDAO datDoAnDAO = new DatDoAnDAO();
    private DoAn modelDoAn;
    private List<DoAn> danhSachDoAn;
    private final List<ChiTietDonHangDTO> danhSachChiTietDonHang = new ArrayList<>();

    /**
     * Creates new form DatDoJFrame
     */
    public DatDoJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        doAnModel.addColumn("Tên Món");
        doAnModel.addColumn("Giá");

        chiTietModel.addColumn("ID Món");
        chiTietModel.addColumn("Tên Món");
        chiTietModel.addColumn("Số Lượng");
        chiTietModel.addColumn("Tổng Giá");

        loadSanPham(1);
    }

    void loadChiTietDonHang() {
        chiTietModel.setRowCount(0);
        long tongTien = 0;
        for (var chiTiet : danhSachChiTietDonHang) {
            chiTietModel.addRow(new Object[]{
                    chiTiet.getId_san_pham(),
                    chiTiet.getTen_sp(),
                    chiTiet.getSoLuong(),
                    PriceUtils.formatCurrency(chiTiet.getTongTien())
            });
            tongTien += chiTiet.getTongTien();
        }
        tblDanhSach.setModel(chiTietModel);

        txtTongTien.setText(PriceUtils.formatCurrency(tongTien));
    }

    void loadSanPham(int danhMuc) {
        doAnModel.setRowCount(0);
        danhSachDoAn = doAnDAO.danhSachSanPham(danhMuc);
        for (var doAn : danhSachDoAn) {
            doAnModel.addRow(new Object[]{
                    doAn.getTen_sp(),
                    PriceUtils.formatCurrency(doAn.getGia_sp())
            });
        }
        if (danhMuc == 1) {
            tblDoUong.setModel(doAnModel);
        } else {
            tblDoAn.setModel(doAnModel);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel36 = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        txtTongTien = new javax.swing.JLabel();
        btnDatDo = new javax.swing.JButton();
        lblDatDo = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDoUong = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDoAn = new javax.swing.JTable();
        jLabel37 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        btnCong = new javax.swing.JToggleButton();
        btnTru = new javax.swing.JToggleButton();
        btnThem = new javax.swing.JButton();
        txtTenMon = new javax.swing.JLabel();
        txtGia = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDanhSach = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreaGhiChu = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTongTien.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel34.setText("Tổng Tiền:");

        txtTongTien.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N

        btnDatDo.setBackground(new java.awt.Color(255, 204, 204));
        btnDatDo.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnDatDo.setForeground(new java.awt.Color(255, 153, 153));
        btnDatDo.setText("Đặt Đồ");
        btnDatDo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatDoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout lblTongTienLayout = new javax.swing.GroupLayout(lblTongTien);
        lblTongTien.setLayout(lblTongTienLayout);
        lblTongTienLayout.setHorizontalGroup(
            lblTongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblTongTienLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel34)
                .addGroup(lblTongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(lblTongTienLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(184, Short.MAX_VALUE))
                    .addGroup(lblTongTienLayout.createSequentialGroup()
                        .addGap(52, 295, Short.MAX_VALUE)
                        .addComponent(btnDatDo)
                        .addGap(29, 29, 29))))
        );
        lblTongTienLayout.setVerticalGroup(
            lblTongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblTongTienLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(lblTongTienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txtTongTien))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblTongTienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDatDo)
                .addGap(15, 15, 15))
        );

        lblDatDo.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        lblDatDo.setForeground(new java.awt.Color(255, 153, 153));
        lblDatDo.setText("Đặt Đồ Ăn Uống");

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tblDoUong.setBackground(new java.awt.Color(255, 204, 204));
        tblDoUong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Món", "Giá"
            }
        ));
        tblDoUong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDoUongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDoUong);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Đặt Đồ Uống", jPanel2);
	jTabbedPane1.addChangeListener(e -> {
            int selectedIndex = jTabbedPane1.getSelectedIndex();
            if (selectedIndex == 0) {
                loadSanPham(1);
            } else if (selectedIndex == 1) {
                loadSanPham(2);
            }
        });
        tblDoAn.setBackground(new java.awt.Color(255, 204, 204));
        tblDoAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tên", "Giá"
            }
        ));
        tblDoAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDoAnMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblDoAn);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Đặt Đồ Ăn", jPanel3);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setText("Tên:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setText("Giá:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel3.setText("Số Lượng:");

        btnCong.setText("+");
        btnCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCongActionPerformed(evt);
            }
        });

        btnTru.setText("-");
        btnTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(255, 204, 204));
        btnThem.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 153, 153));
        btnThem.setText("Thêm ");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        txtTenMon.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N

        txtGia.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N

        btnXoa.setBackground(new java.awt.Color(255, 204, 204));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 153, 153));
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(txtTenMon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(292, 292, 292))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTru, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCong, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtGia, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnThem)
                        .addGap(45, 45, 45))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCong)
                    .addComponent(btnTru)
                    .addComponent(txtTenMon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtGia))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnThem)
                        .addComponent(btnXoa)))
                .addGap(18, 18, 18))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tblDanhSach.setBackground(new java.awt.Color(255, 204, 204));
        tblDanhSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Món", "Tên Món", "Số Lượng", "Tổng Giá"
            }
        ));
        tblDanhSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDanhSachMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDanhSach);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(192, 192, 192))
        );

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Ghi chú:");

        txtAreaGhiChu.setBackground(new java.awt.Color(255, 204, 204));
        txtAreaGhiChu.setColumns(20);
        txtAreaGhiChu.setRows(5);
        jScrollPane4.setViewportView(txtAreaGhiChu);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(408, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                    .addContainerGap(31, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel36)
                        .addGap(432, 432, 432)
                        .addComponent(jLabel37))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDatDo)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDatDo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel37)))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDatDoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatDoActionPerformed
        if(StringUtils.isEmpty(Auth.currentUserTenDangNhap)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng đăng nhập để đặt đồ ăn uống", "Thông báo", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (danhSachChiTietDonHang.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng thêm món ăn hoặc đồ uống vào đơn hàng", "Thông báo", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        var idTk = datDoAnDAO.getIdTk(Auth.currentUserTenDangNhap);
        if (idTk == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Không tìm thấy tài khoản của bạn", "Thông báo", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        var tongTien = danhSachChiTietDonHang.stream()
                .mapToLong(ChiTietDonHangDTO::getTongTien)
                .sum();
        // var tongTien = 0;
//        for(var p : danhSachChiTietDonHang) {
//            tongTien += p.getTongTien();
//        }
        var result = datDoAnDAO.taoDonHangMoi(idTk, tongTien);
        if(result == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Đặt đồ ăn uống thất bại", "Thông báo", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Lưu chi tiết đơn hàng
        datDoAnDAO.luuChiTietDonHang(result, danhSachChiTietDonHang);

        javax.swing.JOptionPane.showMessageDialog(this, "Đặt đồ ăn uống thành công", "Thông báo", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        // Reset danh sách chi tiết đơn hàng
        danhSachChiTietDonHang.clear();
        loadChiTietDonHang();
        txtTenMon.setText("");
        txtGia.setText("");
        txtSoLuong.setText("1");
        modelDoAn = null;
        // Cập nhật lại tổng tiền
        txtTongTien.setText(PriceUtils.formatCurrency(0));
    }//GEN-LAST:event_btnDatDoActionPerformed

    private void tblDoUongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDoUongMouseClicked
        var selectedRow = tblDoUong.getSelectedRow();
        if (selectedRow >= 0) {
            modelDoAn = danhSachDoAn.get(selectedRow);
            txtTenMon.setText(modelDoAn.getTen_sp());
            txtGia.setText(PriceUtils.formatCurrency(modelDoAn.getGia_sp()));
            txtSoLuong.setText("1");
        }
    }//GEN-LAST:event_tblDoUongMouseClicked

    private void tblDoAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDoAnMouseClicked
        var selectedRow = tblDoAn.getSelectedRow();
        if (selectedRow >= 0) {
            modelDoAn = danhSachDoAn.get(selectedRow);
            txtTenMon.setText(modelDoAn.getTen_sp());
            txtGia.setText(PriceUtils.formatCurrency(modelDoAn.getGia_sp()));
            txtSoLuong.setText("1");
        }
    }//GEN-LAST:event_tblDoAnMouseClicked

    private void btnCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCongActionPerformed
        try {
            int soLuong = Integer.parseInt(txtSoLuong.getText());
            soLuong++;
            txtSoLuong.setText(String.valueOf(soLuong));
        } catch (NumberFormatException e) {
            txtSoLuong.setText("1");
        }
    }//GEN-LAST:event_btnCongActionPerformed

    private void btnTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruActionPerformed
        try {
            int soLuong = Integer.parseInt(txtSoLuong.getText());
            if (soLuong <= 1) {
                javax.swing.JOptionPane.showMessageDialog(this, "Số lượng không thể nhỏ hơn 1", "Thông báo", javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            soLuong--;
            txtSoLuong.setText(String.valueOf(soLuong));
        } catch (NumberFormatException e) {
            txtSoLuong.setText("1");
        }
    }//GEN-LAST:event_btnTruActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        var soLuong = Integer.parseInt(txtSoLuong.getText());
        if (soLuong <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Số lượng phải lớn hơn 0", "Thông báo", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (modelDoAn == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn món ăn hoặc đồ uống", "Thông báo", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        var chiTietDonHang = new ChiTietDonHangDTO(modelDoAn.getId_san_pham(), modelDoAn.getTen_sp(), soLuong, modelDoAn.getGia_sp(), modelDoAn.getId_danh_muc());

        var existingChiTiet = danhSachChiTietDonHang.stream()
                .filter(ct -> ct.getId_san_pham() == chiTietDonHang.getId_san_pham())
                .findFirst();
        if (existingChiTiet.isPresent()) {
            // Nếu món ăn đã tồn tại, cập nhật số lượng và tổng giá
            ChiTietDonHangDTO existing = existingChiTiet.get();
            existing.setSoLuong(existing.getSoLuong() + chiTietDonHang.getSoLuong());
            existing.setTongTien((long) existing.getSoLuong() * existing.getGia_sp());
        } else {
            // Nếu món ăn chưa tồn tại, thêm mới
            chiTietDonHang.setTongTien((long) chiTietDonHang.getSoLuong() * chiTietDonHang.getGia_sp());
            chiTietDonHang.setDoAn(new DoAn(modelDoAn));
            danhSachChiTietDonHang.add(chiTietDonHang);
        }
        loadChiTietDonHang();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (modelDoAn == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Vui lòng chọn món ăn hoặc đồ uống", "Thông báo", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        danhSachChiTietDonHang.stream()
                .filter(ct -> ct.getId_san_pham() == modelDoAn.getId_san_pham())
                .findFirst()
                .ifPresent(ct -> {
                    danhSachChiTietDonHang.remove(ct);
                    loadChiTietDonHang();
                    txtTenMon.setText("");
                    txtGia.setText("");
                    txtSoLuong.setText("1");
                    modelDoAn = null;
                });
    }//GEN-LAST:event_btnXoaActionPerformed

    private void tblDanhSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDanhSachMouseClicked
        var selectedRow = tblDanhSach.getSelectedRow();
        if (selectedRow >= 0) {
            var chiTiet = danhSachChiTietDonHang.get(selectedRow);
            modelDoAn = chiTiet.getDoAn();
            txtTenMon.setText(modelDoAn.getTen_sp());
            txtGia.setText(PriceUtils.formatCurrency(modelDoAn.getGia_sp()));
            txtSoLuong.setText(String.valueOf(chiTiet.getSoLuong()));
        }
    }//GEN-LAST:event_tblDanhSachMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatDoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatDoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatDoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatDoJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatDoJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCong;
    private javax.swing.JButton btnDatDo;
    private javax.swing.JButton btnThem;
    private javax.swing.JToggleButton btnTru;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblDatDo;
    private javax.swing.JPanel lblTongTien;
    private javax.swing.JTable tblDanhSach;
    private javax.swing.JTable tblDoAn;
    private javax.swing.JTable tblDoUong;
    private javax.swing.JTextArea txtAreaGhiChu;
    private javax.swing.JLabel txtGia;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JLabel txtTenMon;
    private javax.swing.JLabel txtTongTien;
    // End of variables declaration//GEN-END:variables
}