/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ui;

import DAO.TaiKhoanDAO;
import Utils.Auth;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import Utils.KetNoiDB;
import Utils.Auth;

/**
 *
 * @author ASUS
 */
public class MainUseVip extends javax.swing.JFrame {

    private int thoiGianConLai;
    private double soDu;
    private double giaGio = 20000; // Giá giờ chơi

    /**
     * Creates new form MainUseVip
     */
    public MainUseVip() {
        initComponents();
         // ✅ Lấy số dư từ Auth sau khi login
        soDu = Auth.currentUserSoDu;
        thoiGianConLai = (int) ((soDu / giaGio) * 3600);

        // Hiển thị số dư ban đầu
        txtSoDu.setText(String.format("%.0f VND", soDu));

        // (Tùy chọn) Hiển thị tên người dùng đang đăng nhập
        // lblTaiKhoan.setText("Xin chào: " + Auth.currentUserTenDangNhap);
        batDauDemNguoc();
    }

     private void batDauDemNguoc() {
        TaiKhoanDAO tkD = new TaiKhoanDAO();
        javax.swing.Timer timer = new javax.swing.Timer(1000, e -> {
            if (thoiGianConLai > 0) {
                thoiGianConLai--;
                soDu -= giaGio / 3600; // Trừ tiền mỗi giây

                txtThoiGian.setText(formatTime(thoiGianConLai));
                txtSoDu.setText(String.format("%.0f VND", soDu));

                // ✅ Nếu số dư <= 1 thì tự động đăng xuất và cập nhật số dư
                if (soDu <= 1) {
                    tkD.updateStatus(Auth.currentUserTenDangNhap);
                    System.out.println("Current USername: " + Auth.currentUserTenDangNhap);
                    ((javax.swing.Timer) e.getSource()).stop(); // Dừng timer

                    // 🔁 Cập nhật số dư vào DB giống btnDangXuat
                    try (Connection con = KetNoiDB.getConnection()) {
                        String sql = "UPDATE Tai_Khoan SET so_du = ? WHERE ten_dang_nhap = ?";
                        try (PreparedStatement ps = con.prepareStatement(sql)) {
                            ps.setDouble(1, soDu);
                            ps.setString(2, Auth.currentUserTenDangNhap);
                            int rows = ps.executeUpdate();
                            if (rows > 0) {
                                System.out.println("✅ Cập nhật số dư thành công (TỰ ĐỘNG ĐĂNG XUẤT)");
                            }
                        }
                    } catch (SQLException ex) {
                        System.err.println("❌ Lỗi khi cập nhật số dư (TỰ ĐỘNG):");
                        ex.printStackTrace();
                    } catch (Exception exp) {
                        System.out.println("Error : " + exp);
                    }

                    JOptionPane.showMessageDialog(this, "Số dư không đủ! Tự động đăng xuất.");

                    this.dispose(); // Đóng form hiện tại

                    // Reset Auth
                    Auth.currentUserTenDangNhap = null;
                    Auth.currentUserVaiTro = null;
                    Auth.currentUserSoDu = 0;

                    // Mở lại form đăng nhập
                    new DangNhapVip().setVisible(true);
                    return;
                }

            } else {
                ((javax.swing.Timer) e.getSource()).stop();
                JOptionPane.showMessageDialog(this, "Hết giờ! Vui lòng nạp thêm tiền.");
                this.dispose();
                new DangNhapJFrame().setVisible(true); // Đăng xuất về login
            }
        });
        timer.start();
    }

    private String formatTime(int seconds) {
        int h = seconds / 3600;
        int m = (seconds % 3600) / 60;
        int s = seconds % 60;
        return String.format("%02d:%02d:%02d", h, m, s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnThoiGian1 = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        txtThoiGian = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSoDu = new javax.swing.JTextField();
        lblTitle1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JChat = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        JDoAn = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 153, 153));
        lblTitle.setText("Học không chơi đánh rơi tuổi trẻ !!!");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/z6858304559359_76a522449ad81ca61e0eb390388e54fe.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        btnThoiGian1.setBackground(new java.awt.Color(255, 204, 204));
        btnThoiGian1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnThoiGian1.setForeground(new java.awt.Color(255, 153, 153));
        btnThoiGian1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Alarm.png"))); // NOI18N
        btnThoiGian1.setText("Thời Gian");
        btnThoiGian1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoiGian1ActionPerformed(evt);
            }
        });

        btnDangXuat.setBackground(new java.awt.Color(255, 204, 204));
        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(255, 153, 153));
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Exit.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        txtThoiGian.setEditable(false);
        txtThoiGian.setBackground(new java.awt.Color(255, 204, 204));
        txtThoiGian.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setText("Thời gian");

        jLabel3.setText("Số dư");

        txtSoDu.setEditable(false);
        txtSoDu.setBackground(new java.awt.Color(255, 204, 204));
        txtSoDu.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblTitle1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 153, 153));
        lblTitle1.setText("Chơi không học có vẻ vui hơn =))))");

        jLabel4.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("VIP");

        jMenu1.setText("Hệ thống");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });

        JChat.setText("Đồ ăn");
        jMenu1.add(JChat);

        jMenu3.setText("Đổi mật khẩu");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Hỗ trợ");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });

        JDoAn.setText("Chat");
        jMenu2.add(JDoAn);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(btnThoiGian1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 136, Short.MAX_VALUE)
                .addComponent(btnDangXuat)
                .addGap(87, 87, 87))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(lblTitle1)))
                .addContainerGap(73, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(233, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(29, 29, 29)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtThoiGian)
                        .addComponent(txtSoDu, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                    .addGap(83, 83, 83)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThoiGian1)
                            .addComponent(btnDangXuat)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel4)))
                .addContainerGap(85, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(402, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtSoDu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        // Mở form Đổi mật khẩu (JDialog)
        DoiMatKhauJDialog doiMatKhau = new DoiMatKhauJDialog(this, true); // true = modal
        doiMatKhau.setLocationRelativeTo(this); // Hiển thị ở giữa MainUse1
        doiMatKhau.setVisible(true); // Hiển thị dialog
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        //          ChatJFrame chatForm = new ChatJFrame();
        //    chatForm.setLocationRelativeTo(null); // Form hiện giữa màn hình
        //    chatForm.setVisible(true);
        //    // this.dispose(); // Nếu muốn đóng form hiện tại khi mở form mới
        DatDoJFrame datDoForm = new DatDoJFrame();
        datDoForm.setLocationRelativeTo(null); // Form hiện giữa màn hình
        datDoForm.setVisible(true);
        // this.dispose(); // Đóng form hiện tại nếu cần
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        //        DatDoJFrame datDoForm = new DatDoJFrame();
        //    datDoForm.setLocationRelativeTo(null); // Form hiện giữa màn hình
        //    datDoForm.setVisible(true);
        //    // this.dispose(); // Đóng form hiện tại nếu cần
        ChatJFrame chatForm = new ChatJFrame();
        chatForm.setLocationRelativeTo(null); // Form hiện giữa màn hình
        chatForm.setVisible(true);
        // this.dispose(); // Nếu muốn đóng form hiện tại khi mở form mới
    }//GEN-LAST:event_jMenu2MouseClicked

    private void btnThoiGian1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoiGian1ActionPerformed

    }//GEN-LAST:event_btnThoiGian1ActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
     TaiKhoanDAO tkDAO = new TaiKhoanDAO();
        int confirm = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc chắn muốn đăng xuất?",
                "Xác nhận", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            // 1. Cập nhật số dư vào DB
            try (Connection con = KetNoiDB.getConnection()) {
                String sql = "UPDATE Tai_Khoan SET so_du = ? WHERE ten_dang_nhap = ?";
                try (PreparedStatement ps = con.prepareStatement(sql)) {
                    ps.setDouble(1, soDu); // soDu là biến giảm theo Timer
                    ps.setString(2, Auth.currentUserTenDangNhap);
                    int rows = ps.executeUpdate();
                    if (rows > 0) {
                        System.out.println("Cập nhật số dư thành công!");
                    }
                    tkDAO.updateStatus(Auth.currentUserTenDangNhap);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật số dư: " + e.getMessage());
                e.printStackTrace();
            }

            // 2. Reset thông tin người dùng trong Auth
            Auth.currentUserTenDangNhap = null;
            Auth.currentUserVaiTro = null;
            Auth.currentUserSoDu = 0;

            // 3. Đóng form và quay lại đăng nhập
            this.dispose();
            new DangNhapVip().setVisible(true);
        }
    }//GEN-LAST:event_btnDangXuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUseVip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUseVip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUseVip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUseVip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUseVip().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JChat;
    private javax.swing.JMenu JDoAn;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnThoiGian1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JTextField txtSoDu;
    private javax.swing.JTextField txtThoiGian;
    // End of variables declaration//GEN-END:variables
}
