/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ui;

import DAO.MayTinhDAO;
import DAO.TaiKhoanDAO;
import Utils.Auth;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import Utils.KetNoiDB;
import Utils.Auth;
import Utils.HostUtil;

/**
 *
 * @author ASUS
 */
public class MainUse1 extends javax.swing.JFrame {

    private int thoiGianConLai;
    private double soDu;
    private double giaGio = 10000; // Giá giờ chơi

    /**
     * Creates new form MainUse1
     */
    public MainUse1() {
        initComponents();

        // ✅ Lấy số dư từ Auth sau khi login
        soDu = Auth.currentUserSoDu;
        thoiGianConLai = (int) ((soDu / giaGio) * 3600);

        // Hiển thị số dư ban đầu
        txtSoDu.setText(String.format("%.0f VND", soDu));

        // (Tùy chọn) Hiển thị tên người dùng đang đăng nhập
        // lblTaiKhoan.setText("Xin chào: " + Auth.currentUserTenDangNhap);
        batDauDemNguoc();
    }

    private void batDauDemNguoc() {
        TaiKhoanDAO tkD = new TaiKhoanDAO();
        javax.swing.Timer timer = new javax.swing.Timer(1000, e -> {
            if (thoiGianConLai > 0) {
                thoiGianConLai--;
                soDu -= giaGio / 3600; // Trừ tiền mỗi giây

                txtThoiGian.setText(formatTime(thoiGianConLai));
                txtSoDu.setText(String.format("%.0f VND", soDu));

                // ✅ Nếu số dư <= 1 thì tự động đăng xuất và cập nhật số dư
                if (soDu <= 1) {
                    tkD.updateStatus(Auth.currentUserTenDangNhap);
                    System.out.println("Current USername: " + Auth.currentUserTenDangNhap);
                    ((javax.swing.Timer) e.getSource()).stop(); // Dừng timer

                    // 🔁 Cập nhật số dư vào DB giống btnDangXuat
                    try (Connection con = KetNoiDB.getConnection()) {
                        String sql = "UPDATE Tai_Khoan SET so_du = ? WHERE ten_dang_nhap = ?";
                        try (PreparedStatement ps = con.prepareStatement(sql)) {
                            ps.setDouble(1, soDu);
                            ps.setString(2, Auth.currentUserTenDangNhap);
                            int rows = ps.executeUpdate();
                            if (rows > 0) {
                                System.out.println("✅ Cập nhật số dư thành công (TỰ ĐỘNG ĐĂNG XUẤT)");
                            }
                        }
                    } catch (SQLException ex) {
                        System.err.println("❌ Lỗi khi cập nhật số dư (TỰ ĐỘNG):");
                        ex.printStackTrace();
                    } catch (Exception exp) {
                        System.out.println("Error : " + exp);
                    }

                    JOptionPane.showMessageDialog(this, "Số dư không đủ! Tự động đăng xuất.");

                    this.dispose(); // Đóng form hiện tại

                    // Reset Auth
                    Auth.currentUserTenDangNhap = null;
                    Auth.currentUserVaiTro = null;
                    Auth.currentUserSoDu = 0;

                    // Mở lại form đăng nhập
                    new DangNhapJFrame().setVisible(true);
                    return;
                }

            } else {
                ((javax.swing.Timer) e.getSource()).stop();
                JOptionPane.showMessageDialog(this, "Hết giờ! Vui lòng nạp thêm tiền.");
                this.dispose();
                new DangNhapJFrame().setVisible(true); // Đăng xuất về login
            }
        });
        timer.start();
    }

    private String formatTime(int seconds) {
        int h = seconds / 3600;
        int m = (seconds % 3600) / 60;
        int s = seconds % 60;
        return String.format("%02d:%02d:%02d", h, m, s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollBar1 = new javax.swing.JScrollBar();
        jLabel2 = new javax.swing.JLabel();
        ThoiGian = new javax.swing.JLabel();
        btnDangXuat = new javax.swing.JButton();
        btnThoiGian1 = new javax.swing.JButton();
        txtThoiGian = new javax.swing.JTextField();
        txtSoDu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblTitle2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JChat = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        JDoAn = new javax.swing.JMenu();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/z6858304559359_76a522449ad81ca61e0eb390388e54fe.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");

        btnDangXuat.setBackground(new java.awt.Color(255, 204, 204));
        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(255, 153, 153));
        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Exit.png"))); // NOI18N
        btnDangXuat.setText("Đăng xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });

        btnThoiGian1.setBackground(new java.awt.Color(255, 204, 204));
        btnThoiGian1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btnThoiGian1.setForeground(new java.awt.Color(255, 153, 153));
        btnThoiGian1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Alarm.png"))); // NOI18N
        btnThoiGian1.setText("Thời Gian");
        btnThoiGian1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoiGian1ActionPerformed(evt);
            }
        });

        txtThoiGian.setEditable(false);
        txtThoiGian.setBackground(new java.awt.Color(255, 204, 204));
        txtThoiGian.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtSoDu.setEditable(false);
        txtSoDu.setBackground(new java.awt.Color(255, 204, 204));
        txtSoDu.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setText("Thời gian");

        jLabel3.setText("Số dư");

        lblTitle1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblTitle1.setForeground(new java.awt.Color(255, 153, 153));
        lblTitle1.setText("Học không chơi đánh rơi tuổi trẻ !!!");

        lblTitle2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lblTitle2.setForeground(new java.awt.Color(255, 153, 153));
        lblTitle2.setText("Chơi không học có vẻ vui hơn =))))");

        jMenu1.setText("Hệ thống");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });

        JChat.setText("Đồ ăn");
        jMenu1.add(JChat);

        jMenu3.setText("Đổi mật khẩu");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Hỗ trợ");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });

        JDoAn.setText("Chat");
        jMenu2.add(JDoAn);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ThoiGian)
                .addGap(135, 135, 135))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(lblTitle2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblTitle1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThoiGian1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDangXuat))
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoDu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnThoiGian1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnDangXuat)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtThoiGian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSoDu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(ThoiGian)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        TaiKhoanDAO tkDAO = new TaiKhoanDAO();
        int confirm = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc chắn muốn đăng xuất?",
                "Xác nhận", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            // 1. Cập nhật số dư vào DB
            try (Connection con = KetNoiDB.getConnection()) {
                String sql = "UPDATE Tai_Khoan SET so_du = ? WHERE ten_dang_nhap = ?";
                try (PreparedStatement ps = con.prepareStatement(sql)) {
                    ps.setDouble(1, soDu); // soDu là biến giảm theo Timer
                    ps.setString(2, Auth.currentUserTenDangNhap);
                    int rows = ps.executeUpdate();
                    if (rows > 0) {
                        System.out.println("Cập nhật số dư thành công!");
                    }
                    tkDAO.updateStatus(Auth.currentUserTenDangNhap);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật số dư: " + e.getMessage());
                e.printStackTrace();
            }

            // 2. Reset thông tin người dùng trong Auth
            Auth.currentUserTenDangNhap = null;
            Auth.currentUserVaiTro = null;
            Auth.currentUserSoDu = 0;

            // 3. Đóng form và quay lại đăng nhập
            this.dispose();
            new DangNhapJFrame().setVisible(true);
        }
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
//          ChatJFrame chatForm = new ChatJFrame();
//    chatForm.setLocationRelativeTo(null); // Form hiện giữa màn hình
//    chatForm.setVisible(true);
//    // this.dispose(); // Nếu muốn đóng form hiện tại khi mở form mới
        DatDoJFrame datDoForm = new DatDoJFrame();
        datDoForm.setLocationRelativeTo(null); // Form hiện giữa màn hình
        datDoForm.setVisible(true);
        // this.dispose(); // Đóng form hiện tại nếu cần
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
//        DatDoJFrame datDoForm = new DatDoJFrame();
//    datDoForm.setLocationRelativeTo(null); // Form hiện giữa màn hình
//    datDoForm.setVisible(true);
//    // this.dispose(); // Đóng form hiện tại nếu cần
        ChatJFrame chatForm = new ChatJFrame();
        chatForm.setLocationRelativeTo(null); // Form hiện giữa màn hình
        chatForm.setVisible(true);
        // this.dispose(); // Nếu muốn đóng form hiện tại khi mở form mới
    }//GEN-LAST:event_jMenu2MouseClicked

    private void btnThoiGian1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoiGian1ActionPerformed


    }//GEN-LAST:event_btnThoiGian1ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        // Mở form Đổi mật khẩu (JDialog)
        DoiMatKhauJDialog doiMatKhau = new DoiMatKhauJDialog(this, true); // true = modal
        doiMatKhau.setLocationRelativeTo(this); // Hiển thị ở giữa MainUse1
        doiMatKhau.setVisible(true); // Hiển thị dialog
    }//GEN-LAST:event_jMenu3MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        MayTinhDAO mtDao = new MayTinhDAO();
        String hostName = HostUtil.getHostname();
        mtDao.updateStatus(hostName, "Đang tắt");
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUse1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUse1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUse1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUse1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUse1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu JChat;
    private javax.swing.JMenu JDoAn;
    private javax.swing.JLabel ThoiGian;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnThoiGian1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblTitle2;
    private javax.swing.JTextField txtSoDu;
    private javax.swing.JTextField txtThoiGian;
    // End of variables declaration//GEN-END:variables
}
